// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCGPlpeH2qcHDkNXXGzr0vBX-cnSGCWKc0',
    appId: '1:674903063868:web:12d68ff2d9f66cd08bb239',
    messagingSenderId: '674903063868',
    projectId: 'tinydroplets',
    authDomain: 'tinydroplets.firebaseapp.com',
    databaseURL: 'https://tinydroplets-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'tinydroplets.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCFNuadE5Wbf5_F3Q5uEFMVkT6wuQJ4K9s',
    appId: '1:674903063868:android:92ba495434d1f4718bb239',
    messagingSenderId: '674903063868',
    projectId: 'tinydroplets',
    databaseURL: 'https://tinydroplets-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'tinydroplets.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC5koNMZXzgsws8BLwiyzY4SRuGRiRIuUM',
    appId: '1:674903063868:ios:74052dace4c8e2958bb239',
    messagingSenderId: '674903063868',
    projectId: 'tinydroplets',
    databaseURL: 'https://tinydroplets-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'tinydroplets.firebasestorage.app',
    iosBundleId: 'com.tinydroplets.tinydroplets',
  );
}
